### ISSUE TITLE
CTD on plugin reload

### ISSUE THREAD

**Issue by maxhille** [abieberbach/goplane#1]
Hi Andreas,

I was also looking into writing X-Plane plugins with Go recently. I have yet to solve the problem, that on plugin reload (vie the SDK method), my X-Plane (11.41,Ubuntu,Steam) crashes when I overwrite the .xpl with a new builds artifact.

As I am really a noob when it comes to shared libraries, C and all that real world stuff, I was happy to find your project here. So I built your example to see if you have the right magic sauce but to no avail, it also crashes for me.

Did you experience this problem, too? I am still looking forward to solving that an write X-Plane plugins in Go, so I am very happy about any help here.

**Comment by zodiac1214** [comment]
@maxhille have you solved this issue? do you know what the bug is?

**Comment by maxhille** [comment]
@zodiac1214 I researched this back then and IIRC (mea culpa - should've documented my findings) this is a CGO limitation. As such I will close this issue here. We just have to live with reloading the sim and maybe doing more work in pure Go unit tests (which is a good idea anyway).
